// src/main/java/com/plasturgie/app/dto/ChangePasswordRequestDTO.java
package com.plasturgie.app.dto;

import lombok.Data;
import lombok.NoArgsConstructor;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

@Data
@NoArgsConstructor
public class ChangePasswordRequestDTO {

    @NotBlank(message = "Current password is required.")
    private String oldPassword;

    @NotBlank(message = "New password is required.")
    @Size(min = 8, message = "New password must be at least 8 characters long.") 
    // Add other password policy annotations if needed (e.g., regex for complexity)
    private String newPassword;

	public String getOldPassword() {
		return oldPassword;
	}

	public void setOldPassword(String oldPassword) {
		this.oldPassword = oldPassword;
	}

	public String getNewPassword() {
		return newPassword;
	}

	public void setNewPassword(String newPassword) {
		this.newPassword = newPassword;
	}

    // Getters and setters are generated by @Data
}