// src/main/java/com/plasturgie/app/dto/CourseDetailResponseDTO.java
package com.plasturgie.app.dto;

import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor; // For default constructor
import java.util.List;
import java.util.ArrayList;

// Assuming these DTOs are defined:
// - CourseModuleWithLessonsDTO (has moduleId, title, description, order, List<String> lessons)
// - ReviewDetailDTO (has reviewId, user: SimpleUserDTO, rating, comment, createdAt)

@Data
@EqualsAndHashCode(callSuper = true) // Important because it extends CourseListDTO
@NoArgsConstructor // Provides a default no-argument constructor
public class CourseDetailResponseDTO extends CourseListDTO {

    // Fields specific to the detail view that are NOT in CourseListDTO
    // CourseListDTO already has 'description' and 'certificationEligible'
    // CourseListDTO has 'modules' as List<SimpleModuleDTO> (without lessons)
    // CourseListDTO has 'instructors' as List<SimpleInstructorDTO>
    // CourseListDTO has rating, reviewCount, participants

    // New fields for detailed view:
    private List<CourseModuleWithLessonsDTO> detailedModules; // For modules WITH lessons
    private List<ReviewDetailDTO> fullReviews;             // For a list of full review objects

    // Constructor to initialize from a base CourseListDTO and then add detailed fields separately
    public CourseDetailResponseDTO(CourseListDTO baseListDto) {
        super(); // Call the no-arg constructor of CourseListDTO

        // Copy all properties from baseListDto to this instance's inherited fields
        if (baseListDto != null) {
            this.setCourseId(baseListDto.getCourseId());
            this.setTitle(baseListDto.getTitle());
            this.setDescription(baseListDto.getDescription()); // This field is in CourseListDTO
            this.setCategory(baseListDto.getCategory());
            this.setMode(baseListDto.getMode());
            this.setPrice(baseListDto.getPrice());
            this.setCertificationEligible(baseListDto.getCertificationEligible()); // This field is in CourseListDTO
            this.setCreatedAt(baseListDto.getCreatedAt());
            this.setFirstInstructorName(baseListDto.getFirstInstructorName());
            this.setFirstInstructorId(baseListDto.getFirstInstructorId());
            this.setImageUrl(baseListDto.getImageUrl());
            this.setLevel(baseListDto.getLevel());
            this.setStartDate(baseListDto.getStartDate()); // Assumes String startDate in CourseListDTO
            this.setDuration(baseListDto.getDuration());
            this.setRating(baseListDto.getRating());
            this.setReviewCount(baseListDto.getReviewCount());
            this.setParticipants(baseListDto.getParticipants());
            this.setLocation(baseListDto.getLocation());
            
            // We copy the SimpleInstructorDTOs and SimpleModuleDTOs to the parent part
            if (baseListDto.getInstructors() != null) {
                this.setInstructors(new ArrayList<>(baseListDto.getInstructors()));
            }
            if (baseListDto.getModules() != null) {
                this.setModules(new ArrayList<>(baseListDto.getModules())); // These are SimpleModuleDTO
            }
        }
        // Initialize new fields specific to CourseDetailResponseDTO
        this.detailedModules = new ArrayList<>();
        this.fullReviews = new ArrayList<>();
    }

	public List<CourseModuleWithLessonsDTO> getDetailedModules() {
		return detailedModules;
	}

	public void setDetailedModules(List<CourseModuleWithLessonsDTO> detailedModules) {
		this.detailedModules = detailedModules;
	}

	public List<ReviewDetailDTO> getFullReviews() {
		return fullReviews;
	}

	public void setFullReviews(List<ReviewDetailDTO> fullReviews) {
		this.fullReviews = fullReviews;
	}

    // Getters and setters for detailedModules and fullReviews are generated by @Data
}